site_name: OptiPass Server

theme:
  name: "readthedocs"

extra:
  version: Version 1.0.1

extra_css:
  - css/tidegates.css
  
plugins:
  - search
  - mkdocstrings

nav:
  - "Home":
    - index.md
    - data.md
    - api.md
  - "Installation":
    - install.md
  - "Documentation":
    - modules.md
    - tests.md
